// import mongoose from 'mongoose';

// const studentSchema = new mongoose.Schema({
//   seatNo: { type: String, required: true, unique: true },
//   name: { type: String, required: true },
//   prn: { type: String, required: true },
//   semester: { type: Number, required: true },
//   results: {
//     sgpi: { type: String },
//     cgpi: { type: String },
//     totalMarks: { type: String },
//     finalResult: { type: String },
//   },
//   // This 'subjects' field allows you to store ANY subject-wise marks
//   // generated by your different frontend logic files.
//   subjects: {
//     type: Map,
//     of: mongoose.Schema.Types.Mixed
//   }
// }, { timestamps: true });

// export default mongoose.model('Student', studentSchema);
